routes/web.php
<?php
use App\Http\Controllers\ApplicantProfileController;
use App\Http\Controllers\AppliedJobController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\ShortlistController;
use Illuminate\Support\Facades\Route;

Auth::routes();

// Route::post('/logout', [ApplicantProfileController::class, 'logout'])->name('logout');
/* All Jobs start */
Route::get('/', [JobController::class, 'index'])->name('index');
Route::get('/recentJobs', [JobController::class, 'recentJobs'])->name('recentJobs');
Route::get('/jobdetails/{id}', [JobController::class, 'jobdetails'])->name('jobdetails');

/* All Jobs end */
Route::group(['middleware' => 'auth'], function () {
    /* User type wise authentication user type 1 for admin ,0 for user  */
    // Route::get('/admin', [LoginController::class, 'index']);
    // Route::get('/create', [LoginController::class, 'create']);
    /* Applicant profile start */
    Route::resource('applicant', ApplicantProfileController::class);
    Route::get('/all-applicants', [ApplicantProfileController::class, 'allapplicants'])->name('allapplicants');
    /*Job Applied start */
    Route::resource('appliedjob', AppliedJobController::class);

    // Route::get('/apply-job', [AppliedJobController::class, 'applyjob'])->name('applyjob');
    Route::get('/all-candidate', [AppliedJobController::class, 'allcandidate'])->name('allcandidate');

// Job Post
    Route::resource('job', JobController::class);
    Route::resource('shortlist', ShortlistController::class);
    //Route::resource('admin', AdminController::class);
    Route::get('/applicantlist/{id}', [JobController::class, 'applicantlist'])->name('applicantlist');
    Route::post('/shortlist/{id}', [ShortlistController::class, 'shortlist'])->name('shortlist');
});

resources/views/frontend/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/frontend/layouts/css.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <title>ANH Group</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
  <meta content="Coderthemes" name="author" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- App favicon -->
  <link rel="shortcut icon" href="{{ asset('frontend/assets/images/logo/ANH_Group_logo_white.jpg') }}">

  <!-- App css -->
  <link href="{{ asset('frontend/assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
  <link href="{{ asset('frontend/assets/css/icons.min.css') }}" rel="stylesheet" type="text/css" />
  <link href="{{ asset('frontend/assets/css/app.min.css') }}" rel="stylesheet" type="text/css" />
  <link href="{{ asset('frontend/assets/libs/summernote/summernote-bs4.css') }}" rel="stylesheet" type="text/css" />

  <link href="{{ asset('frontend/assets/libs/select2/select2.min.css') }}" rel="stylesheet" type="text/css" />

  <link href="{{ asset('frontend/assets/libs/dropzone/dropzone.min.css') }}" rel="stylesheet" type="text/css" />
  <!-- custom css -->
  <link href="{{ asset('frontend/assets/css/custom.css') }}" rel="stylesheet" type="text/css" />
  @yield('style')

  <!-- App css -->

</head>

resources/views/frontend/layouts/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                @php echo date("Y") ;  @endphp &copy; Developed By <a href="https://www.anhgroupbd.com/"><span style="font-style: italic;">ANH Group</span></a> 
            </div>
            <div class="col-md-6">
                <div class="text-md-right footer-links d-none d-sm-block">
                    
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/frontend/layouts/js.blade.php
<div class="rightbar-overlay"></div>

<!-- Vendor js -->
<script src="{{ asset('frontend/assets/js/vendor.min.js') }}"></script>

<!-- Plugin js-->
<script src="{{ asset('frontend/assets/libs/parsleyjs/parsley.min.js') }}"></script>

<!-- Validation init js-->
<script src="{{ asset('frontend/assets/js/pages/form-validation.init.js') }}"></script>

<!-- App js -->
<script src="{{ asset('frontend/assets/js/app.min.js') }}"></script>
<script src="{{ asset('frontend/assets/libs/footable/footable.all.min.js') }}"></script>

<!-- Init js -->
<script src="{{ asset('frontend/assets/js/pages/foo-tables.init.js') }}"></script>
 <!-- Summernote js -->
 <script src="{{ asset('frontend/assets/libs/summernote/summernote-bs4.min.js') }}"></script>

 <!-- Init js -->
 <script src="{{ asset('frontend/assets/js/pages/form-summernote.init.js') }}"></script>
 
 <!-- Select2 js-->
 <script src="{{ asset('frontend/assets/libs/select2/select2.min.js') }}"></script>
 <!-- Dropzone file uploads-->
 <script src="{{ asset('frontend/assets/libs/dropzone/dropzone.min.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/pages/add-product.init.js') }}"></script>
 <script src="{{ asset('frontend/assets/libs/summernote/summernote-bs4.min.js') }}"></script>

 <!-- Init js -->
 <script src="{{ asset('frontend/assets/js/pages/form-summernote.init.js') }}"></script>
 @yield('js')

resources/views/frontend/layouts/master.blade.php
@include('frontend.layouts.css')
<style>
    .container-fluid {
        width: 85%;
        line-height: 2.5;
    }
    
</style>

<body>
    <!-- wrapper  -->
    <div id="wrapper">

        <!-- Topbar Start -->
        @include('frontend.layouts.topbar')
        <!-- end Topbar -->
        @yield('content')
       
   
    <!-- Footer Start -->
    @include('frontend.layouts.footer')
    <!-- end Footer -->

    @include('frontend.layouts.js')

</div>
</body>

resources/views/frontend/layouts/sidebar.blade.php
<div class="left-side-menu">

    <div class="slimscroll-menu">

        <!--- Sidemenu -->
        <div id="sidebar-menu">

            <ul class="metismenu" id="side-menu">

                <li class="menu-title">Navigation</li>

                <li>
                    <a href="javascript: void(0);">
                        <i class="fe-airplay"></i>
                        <span class="badge badge-success badge-pill float-right">4</span>
                        <span> Dashboards </span>
                    </a>
                    <ul class="nav-second-level" aria-expanded="false">
                        <li>
                            <a href="index.html">Dashboard 1</a>
                        </li>

                    </ul>
                </li>
                <li>
                    <a href="javascript: void(0);">
                        <i class="fe-mail"></i>
                        <span> Applicant Profile</span>
                        <span class="menu-arrow"></span>
                    </a>
                    <ul class="nav-second-level" aria-expanded="false">
                        <li>
                            <a href="{{ route('applicant.create') }}">Create</a>
                        </li>
                        <li>
                            <a href="{{ route('allapplicants') }}">list</a>
                        </li>

                    </ul>
                </li>

                <li>
                    <a href="javascript: void(0);">
                        <i class="fe-file-text"></i>
                        <span> Job Post </span>
                        <span class="menu-arrow"></span>
                    </a>
                    <ul class="nav-second-level" aria-expanded="false">
                        @if (Gate::allows('job.create'))
                            <li>
                                <a href="{{ route('job.create') }}">Create</a>
                            </li>
                        @endif
                        {{-- <li>
                            <a href="{{ route('job.create') }}">Create</a>
                        </li> --}}
                        <li>
                            <a href="{{ route('job.index') }}">List</a>
                        </li>


                    </ul>
                </li>
                <li>
                    <a href="javascript: void(0);">
                        <i class="fe-file-text"></i>
                        <span> Candidate</span>
                        <span class="menu-arrow"></span>
                    </a>
                    <ul class="nav-second-level" aria-expanded="false">
                        {{-- @if (Gate::allows('job.create'))
                        <li>
                            <a href="">Create</a>
                        </li>   
                        @endif --}}
                        {{-- <li>
                            <a href="{{ route('job.create') }}">Create</a>
                        </li> --}}
                        <li>
                            <a href="{{ route('appliedjob.index') }}">List</a>
                        </li>


                    </ul>
                </li>

                <li>
                    <a href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                        <i class="nav-icon fas fa-sign-out-alt"></i>
                        <p>
                            {{ __('Logout') }}
                        </p>
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </li>



                <li class="menu-title mt-2">Components</li>




        </div>
        <!-- End Sidebar -->

        <div class="clearfix"></div>

    </div>
    <!-- Sidebar -left -->

</div>

resources/views/frontend/layouts/topbar.blade.php
<div class="navbar-custom">
    <ul class="list-unstyled topnav-menu float-right mb-0">

        <li class="dropdown notification-list">
            <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect waves-light" data-toggle="dropdown"
                href="" role="button" aria-haspopup="false" aria-expanded="false">
                @if (auth()->check())
                    <img src="{{ asset('assets/images/logo/ANH_Group_logo_white.jpg') }}" alt=""
                        class="rounded-circle">{{ Auth::user()->name }}
                @endif
                <span class="pro-user-name ml-1">
                    {{-- {{ Auth::user()->name }} <i class="mdi mdi-chevron-down"></i>  --}}
                </span>
            </a>
            <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                <!-- item-->
                <div class="dropdown-header noti-title">
                    <h6 class="text-overflow m-0">Welcome !</h6>
                </div>
                <div class="dropdown-header noti-title">
                    <h6 class="text-overflow m-0">
                        @if (auth()->check())
                            <span>
                                <a href="{{ route('applicant.edit', auth()->user()->id) }}" class="">Edit
                                    Profile</a></span>
                            </span>
                        @endif


                    </h6>
                </div>
                <div class="dropdown-header noti-title">
                    <h6 class="text-overflow m-0">
                        @if (auth()->check())
                            <span>
                                <a href="{{ route('applicant.show', auth()->user()->id) }}" class="">My
                                    Profile</a></span>
                            </span>
                        @endif

                    </h6>
                </div>
                <div class="dropdown-header noti-title">
                    <h6 class="text-overflow m-0">
                        @if (auth()->check())
                            <span>
                                <a href="{{ route('appliedjob.index') }}" class="">My
                                    Applied jobs</a></span>

                            </span>
                        @endif

                    </h6>
                </div>
                <div class="dropdown-header noti-title">
                    <h6 class="text-overflow m-0">
                        <a href="{{ route('logout') }}"
                            onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                            <i class="nav-icon fas fa-sign-out-alt"></i>
                            <p>
                                {{ __('Logout') }}
                            </p>
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </h6>
                </div>
                <div class="dropdown-divider"></div>
                <a href="javascript:void(0);" class="dropdown-item notify-item">


                </a>

            </div>
        </li>

    </ul>

    <!-- LOGO -->
    <div class="logo-box">
        <a href="index.html" class="logo text-center">
            <span class="logo-lg">
                <img src="{{ asset('assets/images/logo/ANH_Group_logo_white.jpg') }}" alt="" height="60">
                <!-- <span class="logo-lg-text-light">UBold</span> -->
            </span>
            <span class="logo-sm">
                <!-- <span class="logo-sm-text-dark">U</span> -->
                <img src="{{ asset('assets/images/logo/ANH_Group_logo_white.jpg') }}" alt="" height="24">
            </span>
        </a>
    </div>

    <ul class="list-unstyled topnav-menu topnav-menu-left m-0">
        <li>
            <button class="button-menu-mobile waves-effect waves-light">
                <i class="fe-menu"></i>
            </button>
        </li>
        <li class="">
            <a class="nav-link dropdown-toggle waves-effect waves-light" data-toggle="dropdown" href="#"
                role="button" aria-haspopup="false" aria-expanded="false">
                @if (Route::has('login'))
                    <div class="hidden fixed top-0 right-0 px-6 py-4 sm:block topnav">
                        @auth
                            <a href="{{ url('/') }}" class="text-sm text-gray-700 dark:text-gray-500 underline"></a>
                        @else
                            <a href="{{ route('login') }}" class="container-fluid">Log
                                in</a>

                            @if (Route::has('register'))
                                <a href="{{ route('register') }}" class="navbar-header">Register</a>
                            @endif
                        @endauth
                    </div>
                @endif
            </a>

        </li>
    </ul>
</div>