routes/web.php
<?php
use App\Http\Controllers\ApplicantProfileController;
use App\Http\Controllers\AppliedJobController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\ShortlistController;
use Illuminate\Support\Facades\Route;

Auth::routes();

// Route::post('/logout', [ApplicantProfileController::class, 'logout'])->name('logout');
/* All Jobs start */
Route::get('/', [JobController::class, 'index'])->name('index');
Route::get('/recentJobs', [JobController::class, 'recentJobs'])->name('recentJobs');
Route::get('/jobdetails/{id}', [JobController::class, 'jobdetails'])->name('jobdetails');

/* All Jobs end */
Route::group(['middleware' => 'auth'], function () {
    /* User type wise authentication user type 1 for admin ,0 for user  */
    // Route::get('/admin', [LoginController::class, 'index']);
    // Route::get('/create', [LoginController::class, 'create']);
    /* Applicant profile start */
    Route::resource('applicant', ApplicantProfileController::class);
    Route::get('/all-applicants', [ApplicantProfileController::class, 'allapplicants'])->name('allapplicants');
    /*Job Applied start */
    Route::resource('appliedjob', AppliedJobController::class);

    // Route::get('/apply-job', [AppliedJobController::class, 'applyjob'])->name('applyjob');
    Route::get('/all-candidate', [AppliedJobController::class, 'allcandidate'])->name('allcandidate');

// Job Post
    Route::resource('job', JobController::class);
    Route::resource('shortlist', ShortlistController::class);
    //Route::resource('admin', AdminController::class);
    Route::get('/applicantlist/{id}', [JobController::class, 'applicantlist'])->name('applicantlist');
    Route::post('/shortlist/{id}', [ShortlistController::class, 'shortlist'])->name('shortlist');
});

resources/views/frontend/pages/applicant/all_applicants.blade.php
@extends('backend.layouts.master')
@section('content')
    <div class="content-page">
        <div class="content">

            <!-- Start Content-->
            <div class="container-fluid">

                <!-- start page title -->
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box">

                        </div>
                    </div>
                </div>
                <!-- end page title -->
 <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="row mb-2">
                                    <div class="col-sm-4">
                                        <a href="#custom-modal" class="btn btn-danger waves-effect waves-light"
                                            data-animation="fadein" data-plugin="custommodal" data-overlaycolor="#38414a"><i
                                                class="mdi mdi-plus-circle mr-1"></i> Add Customers</a>
                                                {{-- <a href="{{ route('applicant.edit',$applicants->edit) }}">Edit Profile</a> --}}
                                    </div>
                                 </div>
<div class="table-responsive">
                                    <table class="table table-centered table-striped" id="products-datatable">
                                        <thead>
                                            <tr>
                                               <th>Name</th>
                                                <th>Phone</th>
                                                <th>Present Address</th>
                                                <th>Permanent Address</th>
                                               <th>Gender</th>
                                                <th>Resume</th>

                                                {{-- <th>Status</th> --}}
                                                <th style="width: 85px;">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($applicants as $applicant)
                                                <tr>
                                                    {{-- <td>
                                                <div class="custom-control custom-checkbox">
                                                    <input type="checkbox" class="custom-control-input" id="customCheck2">
                                                    <label class="custom-control-label" for="customCheck2">&nbsp;</label>
                                                </div>
                                            </td> --}}

                                                    <td>
                                                        {{ $applicant->name }}
                                                    </td>
                                                    <td>
                                                        {{ $applicant->phone }}
                                                    </td>
                                                    <td>
                                                        {{ $applicant->present_address }}
                                                    </td>
                                                    <td>
                                                        {{ $applicant->permanent_address }}
                                                    </td>
                                                   
                                                    <td>
                                                        {{ $applicant->gender }}
                                                    </td>
                                                    {{-- <td>
                                                        <a href="{{($applicant->resume) }}" class="eye-" alt="" width="100"></a>
                                                        </td> --}}
                                                        <td><a href="{{ asset($applicant->resume) }}" class="fa fa-eye btn btn-primary" style="width:70px;">open</a></td>
                                                    {{-- <td>
                                                        <span class="badge bg-soft-success text-success">Active</span>
                                                    </td> --}}
                                                   
                                                    <td>
                                                        <a href="{{ route('applicant.show', $applicant->id) }}"
                                                            class="btn btn-primary">Details</a>
                                                        <a href="{{ route('applicant.edit', $applicant->id) }}"
                                                            class="btn btn-primary">Edit</a>

                                                        <form action="{{ route('applicant.destroy', $applicant->id) }}"
                                                            method="POST">
                                                            @csrf
                                                            @method('DELETE')
                                                            <button type="submit"
                                                                class="btn btn-danger mt-1">Delete</button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach



                                        </tbody>
                                    </table>
                                </div>

                                <ul class="pagination pagination-rounded justify-content-end mb-0">
                                    <li class="page-item">
                                        <a class="page-link" href="javascript: void(0);" aria-label="Previous">
                                            <span aria-hidden="true">«</span>
                                            <span class="sr-only">Previous</span>
                                        </a>
                                    </li>
                                    <li class="page-item active"><a class="page-link" href="javascript: void(0);">1</a></li>
                                    <li class="page-item"><a class="page-link" href="javascript: void(0);">2</a></li>
                                    <li class="page-item"><a class="page-link" href="javascript: void(0);">3</a></li>
                                    <li class="page-item"><a class="page-link" href="javascript: void(0);">4</a></li>
                                    <li class="page-item"><a class="page-link" href="javascript: void(0);">5</a></li>
                                    <li class="page-item">
                                        <a class="page-link" href="javascript: void(0);" aria-label="Next">
                                            <span aria-hidden="true">»</span>
                                            <span class="sr-only">Next</span>
                                        </a>
                                    </li>
                                </ul>

                            </div> <!-- end card-body-->
                        </div> <!-- end card-->
                    </div> <!-- end col -->
                </div>
                <!-- end row -->

            </div> <!-- container -->

        </div> <!-- content -->

        <!-- Footer Start -->

        <!-- end Footer -->

    </div>
@endsection

resources/views/frontend/pages/applicant/create.blade.php
@extends('backend.layouts.master')
@section('content')
    <div class="content-page" style="justify-content: center;">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card-box">
                            <h4 class="header-title">Applicant Profile</h4>


                            <div class="alert alert-warning d-none fade show">
                                <h4 class="text-warning mt-0">Oh snap!</h4>
                                <p class="mb-0">This form seems to be invalid :(</p>
                            </div>

                            <div class="alert alert-info d-none fade show">
                                <h4 class="text-info mt-0">Yay!</h4>
                                <p class="mb-0">Everything seems to be ok :)</p>
                            </div>

                            <form method="post" action="{{ route('applicant.store') }}" enctype="multipart/form-data">
                                @csrf
                                <div class="col-6 form-group">
                                    <label for="fullname">Present Address * :</label>
                                    <input type="text" class="form-control" name="present_address" id="fullname">
                                </div>
                                <div class="col-6 form-group">
                                    <label for="fullname">Phone * :</label>
                                    <input type="number" class="form-control" name="phone" id="">
                                </div>

                                <div class="col-6 form-group">
                                    <label for="email">Parmanent Address * :</label>
                                    <input type="text"  class="form-control" name="permanent_address"
                                        data-parsley-trigger="change">
                                </div>
                                <div class="col-6 form-group">
                                    <label for="dob">DOB * :</label>
                                    <input type="date"  class="form-control" name="dob"
                                        data-parsley-trigger="change">
                                </div>
                                <div class="col-6 form-group">
                                    <label for="expected_salary">Expected Salary * :</label>
                                    <input type="text"  class="form-control" name="expected_salary"
                                        data-parsley-trigger="change">
                                </div>
                                <div class="col-6 form-group">
                                    <label for="present_salary">Present Salary * :</label>
                                    <input type="text"  class="form-control" name="present_salary"
                                        data-parsley-trigger="change">
                                </div>

                                <div class="col-6 form-group">
                                    <label for="heard">Gender *:</label>
                                    <select id="heard" class="form-control" name="gender">
                                        <option value="">Choose..</option>
                                        <option value="Male">Male</option>
                                        <option value="Female">Female</option>

                                    </select>
                                </div>
                                <div class="col-6 form-group">
                                    <label for="email">Age * :</label>
                                    <input type="text"  class="form-control" name="age"
                                        data-parsley-trigger="change">
                                </div>
                                <div class="col-6 form-group">
                                    <label for="email">Job Experience * :</label>
                                    <input type="text"  class="form-control" name="job_experience"
                                        data-parsley-trigger="change">
                                </div>
                                <div class="col-6 form-group">
                                    <label for="email">Resume * :</label>
                                    <input type="file"  class="form-control" name="resume" 
                                        data-parsley-trigger="change">
                                </div>
                                <div class="col-6 form-group">
                                    <label for="email">Skill * :</label>
                                    <input type="skill"  class="form-control" name="skill"
                                        data-parsley-trigger="change">
                                </div>
                                <div class="responsive" style="responsive:auto">

                                    <div class="card-box">
                                        <div id="container">
                                            <h2>Accademic Qualifications</h2>
                                            <a class="btn btn-success" id="add-new-btn">Add New Row
                                            </a>
                                            <a class="btn btn-danger" id="delete-btn">Delete Row
                                            </a>
                                            <br>
                                            <br>
                                            <table id="employee-table" class="table table-bordered "
                                                style="overflow-x:auto;">
                                                <tr>
                                                    <th>Exam</th>
                                                    <th>Result </th>
                                                    <th>Instituation</th>
                                                    <th>Passing year </th>
                                                  
                                                    
                                                    <th>Action </th>
                                                </tr>
                                            </table>
                                        </div>
                                    </div> <!-- end card-box -->
                                </div> <!-- end col -->

                              <div class="d-none d-sm-block">
                                
                                <div class="card-box">
                                    <div id="container">
                                        <h2>Experience</h2>
                                        <a class="btn btn-success" id="add-experience">Add New Row
                                        </a>
                                        <a class="btn btn-danger" id="delete-experience">Delete Row
                                        </a>
                                        <br>
                                        <br>
                                        <table id="experience-table" class="table table-bordered "
                                            style="overflow-x:auto;">
                                            <tr>
                                                <th>Title</th>
                                                <th>Start Date </th>
                                                <th>End Date </th>
                                                <th>Company</th>
                                                <th>Action </th>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                                    
                                <!-- end card-box -->
                                </div> <!-- end col -->


                                <div class="form-group mb-0">
                                    <input type="submit" class="btn btn-success" value="Apply">
                                </div>

                            </form>

                        </div> <!-- end card-box-->
                    </div> <!-- end col-->
                </div>
            </div> <!-- container -->
        </div> <!-- content -->
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script type="text/javascript">
        /* This event will fire on 'Add New Row' button click */
        $("#add-new-btn").on("click", function() {
           // alert("this is call");
            //calling method to add new row
           addNewRow();
        });
        /* This event will fire on 'Delete Row' button click */
        $("#delete-btn").on("click", function() {
            //calling method to delete the last row
            deleteRow();
        });
        /* This method will add a new row */
        function addNewRow() {
            var rowHtml = '<tr><td><input type="text"name="exam[]" /></td>' +
                '<td><input type="text" name="result[]" /></td>' +
                '<td><input type="text" name="instituations[]" /></td>' +
               
                '<td><input type="text"name="passing_year[]" /></td>'

                +
                '<td><input type="button" class="btn btn-danger" value="delete" onclick="deleteRow(this)" /></td></tr>';
            $("#employee-table").append(rowHtml);
        }
        /* This method will delete a row */
        function deleteRow(ele) {
            var table = $('#employee-table')[0];
            var rowCount = table.rows.length;
            if (rowCount <= 1) {
                alert("There is no row available to delete!");
                return;
            }
            if (ele) {
                //delete specific row
                $(ele).parent().parent().remove();
            } else {
                //delete last row
                table.deleteRow(rowCount - 1);
            }
        }


       
    </script>
    <script>

$("#add-experience").on("click", function() {
            //calling method to add new row
            addNewRowexp();
        });
        /* This event will fire on 'Delete Row' button click */
        $("#delete-experience").on("click", function() {
            //calling method to delete the last row
            deleteRowexp();
        });
        /* This method will add a new row */
        function addNewRowexp() {
            var rowHtml = '<tr><td><input type="text" name="title[]" /></td>' +
                '<td><input type="date" name="start_date[]" /></td>' +
                '<td><input type="date"name="end_date[]" /></td>' +
                '<td><input type="text"name="company[]" /></td>'

                +
                '<td><input type="button" class="btn btn-danger" value="delete" onclick="deleteRowexp(this)" /></td></tr>';
            $("#experience-table").append(rowHtml);
        }
        /* This method will delete a row */
        function deleteRowexp(ele) {
            var table = $('#experience-table')[0];
            var rowCount = table.rows.length;
            if (rowCount <= 1) {
                alert("There is no row available to delete!");
                return;
            }
            if (ele) {
                //delete specific row
                $(ele).parent().parent().remove();
            } else {
                //delete last row
                table.deleteRowexp(rowCount - 1);
            }
        }
    </script>
@endsection

resources/views/frontend/pages/applicant/details_list.blade.php
@extends('frontend.layouts.master')
@section('content')
    <div class="content-page" style="">
        <div class="content">
            <div class="container-fluid">
                   <body>
                    <h3 style="color: green">Name :{{ $applicant->user_id ? $user->name : '' }}</h3>
                       <table  style="width:100%;border:2px;" class="table table-striped">
                        <tr>
                            <th>Present Address:</th>
                            <td> {{ $applicant->present_address }}</td>
                        </tr>

                        <tr>
                            <th>permanent_address:</th>
                            <td>{{ $applicant->permanent_address }}</td>
                        </tr>
                        <tr>
                            <th>Phone:</th>
                            <td>{{ $applicant->phone }}</td>
                        </tr>
                        <tr>
                            <th>Dob :</th>
                            <td>{{ $applicant->dob }}</td>
                        </tr>
                        <tr>
                            <th>Expected Salary:</th>
                            <td>{{ $applicant->expected_salary }}</td>
                        </tr>
                        <tr>
                            <th>Present Salary:</th>
                            <td>{{ $applicant->present_salary }}</td>
                        </tr>
                        <tr>
                            <th> Gender :</th>
                            <td>{{ $applicant->gender }}</td>
                        </tr>
                        <tr>
                            <th> Job Experience :</th>
                            <td>{{ $applicant->job_experience }}</td>
                        </tr>
                    </table>
                    <h3 style="color: rgb(95, 160, 95)">Educations</h3>

                    <table  width="100%" class="table align-middle mb-0 bg-green">
                        <thead style="font-weight: bold;">
                            <tr>
                                <td>Exam</td>
                                <td>Result</td>
                                <td>Instituations </td>
                                <td>Passing year </td>
                            </tr>
                        </thead>

                        <tfoot>
                            <tr>
                                <td colspan="4">All of my educations</td>
                            </tr>
                        </tfoot>

                        <tbody>
                            @foreach ($education as $item)
                                <tr>
                                    <td>{{ $item->exam }}</td>
                                    <td>{{ $item->result }}</td>
                                    <td>{{ $item->instituations }}</td>
                                    <td>{{ $item->passing_year }}</td>

                                </tr>
                            @endforeach
                        </tbody>

                    </table>

                    <h3 style="color: rgb(95, 160, 95)">Experiences</h3>

                    <table  width="100%" class="table align-middle mb-0 bg-green">
                        <thead style="font-weight: bold;">
                            <tr>
                                <td>Designation</td>
                                <td>Start Date</td>
                                <td>End Date </td>
                                <td>Company </td>
                            </tr>
                        </thead>

                        <tfoot>
                            <tr>
                                <td colspan="4">All of my experience</td>
                            </tr>
                        </tfoot>

                        <tbody>
                            @foreach ($experience as $item)
                            <tr>
                                <td>{{ $item->title }}</td>
                                <td>{{ $item->start_date }}</td>
                                <td>{{ $item->end_date }}</td>
                                <td>{{ $item->company }}</td>

                            </tr>
                        @endforeach
                        </tbody>

                    </table>
                </body>
            @endsection

resources/views/frontend/pages/applicant/list.blade.php
@extends('backend.layouts.master')
@section('content')
    <div class="content-page" style="justify-content: center;">
        <div class="content">
            <div class="container-fluid">

                <body>
                    <h3 style="color: green">Name :{{ $applicant->user_id ? $user->name : '' }}</h3>
                       <table border="1" style="width:100%" class="table align-middle mb-0 bg-red">
                        <tr>
                            <th>Present Address:</th>
                            <td> {{ $applicant->present_address }}</td>
                        </tr>

                        <tr>
                            <th>permanent_address:</th>
                            <td>{{ $applicant->permanent_address }}</td>
                        </tr>
                        <tr>
                            <th>Phone:</th>
                            <td>{{ $applicant->phone }}</td>
                        </tr>
                        <tr>
                            <th>Dob :</th>
                            <td>{{ $applicant->dob }}</td>
                        </tr>
                        <tr>
                            <th>Expected Salary:</th>
                            <td>{{ $applicant->expected_salary }}</td>
                        </tr>
                        <tr>
                            <th>Present Salary:</th>
                            <td>{{ $applicant->present_salary }}</td>
                        </tr>
                        <tr>
                            <th> Gender :</th>
                            <td>{{ $applicant->gender }}</td>
                        </tr>
                        <tr>
                            <th> Job Experience :</th>
                            <td>{{ $applicant->job_experience }}</td>
                        </tr>
                    </table>
                    <h3 style="color: rgb(95, 160, 95)">Educations</h3>

                    <table border="1" width="100%" class="table align-middle mb-0 bg-green">
                        <thead style="font-weight: bold;">
                            <tr>
                                <td>Exam</td>
                                <td>Result</td>
                                <td>Instituations </td>
                                <td>Passing year </td>
                            </tr>
                        </thead>

                        <tfoot>
                            <tr>
                                <td colspan="4">All of my educations</td>
                            </tr>
                        </tfoot>

                        <tbody>
                            @foreach ($education as $item)
                                <tr>
                                    <td>{{ $item->exam }}</td>
                                    <td>{{ $item->result }}</td>
                                    <td>{{ $item->instituations }}</td>
                                    <td>{{ $item->passing_year }}</td>

                                </tr>
                            @endforeach
                        </tbody>

                    </table>

                    <h3 style="color: rgb(95, 160, 95)">Experiences</h3>

                    <table border="1" width="100%" class="table align-middle mb-0 bg-green">
                        <thead style="font-weight: bold;">
                            <tr>
                                <td>Designation</td>
                                <td>Start Date</td>
                                <td>End Date </td>
                                <td>Company </td>
                            </tr>
                        </thead>

                        <tfoot>
                            <tr>
                                <td colspan="4">All of my experience</td>
                            </tr>
                        </tfoot>

                        <tbody>
                            @foreach ($experience as $item)
                            <tr>
                                <td>{{ $item->title }}</td>
                                <td>{{ $item->start_date }}</td>
                                <td>{{ $item->end_date }}</td>
                                <td>{{ $item->company }}</td>

                            </tr>
                        @endforeach
                        </tbody>

                    </table>
                </body>
            @endsection