routes/web.php
<?php
use App\Http\Controllers\ApplicantProfileController;
use App\Http\Controllers\AppliedJobController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\ShortlistController;
use Illuminate\Support\Facades\Route;

Auth::routes();

// Route::post('/logout', [ApplicantProfileController::class, 'logout'])->name('logout');
/* All Jobs start */
Route::get('/', [JobController::class, 'index'])->name('index');
Route::get('/recentJobs', [JobController::class, 'recentJobs'])->name('recentJobs');
Route::get('/jobdetails/{id}', [JobController::class, 'jobdetails'])->name('jobdetails');

/* All Jobs end */
Route::group(['middleware' => 'auth'], function () {
    /* User type wise authentication user type 1 for admin ,0 for user  */
    // Route::get('/admin', [LoginController::class, 'index']);
    // Route::get('/create', [LoginController::class, 'create']);
    /* Applicant profile start */
    Route::resource('applicant', ApplicantProfileController::class);
    Route::get('/all-applicants', [ApplicantProfileController::class, 'allapplicants'])->name('allapplicants');
    /*Job Applied start */
    Route::resource('appliedjob', AppliedJobController::class);

    // Route::get('/apply-job', [AppliedJobController::class, 'applyjob'])->name('applyjob');
    Route::get('/all-candidate', [AppliedJobController::class, 'allcandidate'])->name('allcandidate');

// Job Post
    Route::resource('job', JobController::class);
    Route::resource('shortlist', ShortlistController::class);
    //Route::resource('admin', AdminController::class);
    Route::get('/applicantlist/{id}', [JobController::class, 'applicantlist'])->name('applicantlist');
    Route::post('/shortlist/{id}', [ShortlistController::class, 'shortlist'])->name('shortlist');
});

app/Models/Job.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Job extends Model
{
    use HasFactory;

    public function applied_jobs()
    {
        return $this->hasMany(AppliedJob::class,'job_id','id');
    }
}

app/Http/Controllers/JobController.php
<?php

namespace App\Http\Controllers;

use App\Models\ApplicantProfile;
use App\Models\AppliedJob;
use App\Models\Job;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;

class JobController extends Controller
{

    public function index()
    {
        $recentJobs = Job::where('created_at', '>=', date('Y-m-d', strtotime('-30 days')))
            ->count();
        //dd($recentJobs);
        $jobs = Job::paginate(10);
        if (!Auth::check()) {

            return view('frontend.pages.index', compact('jobs', 'recentJobs'));
        } elseif (Auth::user()->type == 1) {

            return view('backend.pages.index', compact('jobs', 'recentJobs'));
        } elseif (Auth::user()->type == 0) {

            return view('frontend.pages.index', compact('jobs', 'recentJobs'));
        }

    }
    public function categories($job_id)
    {
        $job = AppliedJob::all()->where('job_id');
        //$applied = $job->jobs;
        dd($job);
    }
    public function recentJobs()
    {
        //$recentJobs = date('Y-m-d H:i:s');

// Count the jobs that were created within the last 7 days
        $recentJobs = Job::where('created_at', '>=', date('Y-m-d H:i:s', strtotime('-30 days')))
            ->count();
        // dd($recentJobs);
        return view('frontend.pages.index', compact('recentJobs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        // if (!Gate::allows('backend.pages.job.create')) {
        //     abort(403, "You are not allowed!");
        // }
        return view('backend.pages.job.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $job = new Job;
        $job->title = $request->title;
        $job->salary_range = $request->salary_range;
        $job->description = $request->description;
        $job->job_category = $request->job_category;
        $job->job_experience = $request->job_experience;
        $job->job_qualification = $request->job_qualification;
        $job->job_deadline = $request->job_deadline;
        $job->gender = $request->gender;
        $job->location = $request->location;
        //dd($job);

        $job->save();

        session()->flash('message', 'Successfully Save Your Information.');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Job  $job
     * @return \Illuminate\Http\Response
     */
    public function jobdetails($id)
    {

        $job = Job::with('applied_jobs.applicant_profiles.user')->find($id)->toArray();

        dd($job );

//         $applicatnt_ids =  AppliedJob::where('job_id',$id)->pluck('applicant_id');
//          $applicant_list =  ApplicantProfile::whereIn('id',$applicatnt_ids)->get();
// dd($applicant_list);
        return view('frontend.pages.job.job_details', compact('job'));
    }
    public function applicantlist($id)
    {
        // $job = Job::with('applied_jobs.applicant_profiles.users')->find($id)->toArray();
        $applicant_ids = AppliedJob::where('job_id', $id)->pluck('applicant_id');
        $jobs = ApplicantProfile::with('users')->WhereIn('id', $applicant_ids)->get();
        // $applicant = $applicant_list->dob;
        // echo '<pre>';
        // print_r($applicant_list);

        //dd($job);
        return view('backend.pages.job.candidates', compact('jobs'));
    }
    public function edit(Job $job)
    {
        //
    }

    public function update(Request $request, Job $job)
    {
        //
    }

    public function destroy(Job $job)
    {
        //echo "this is delete page";

        $job->delete();
        return redirect()->back();
    }
}

resources/views/frontend/pages/job/all_jobs_.blade.php
@extends('backend.layouts.master')
@section('content')
    <div class="content-page">
        <div class="content">

            <!-- Start Content-->
            <div class="container-fluid">

                <!-- start page title -->
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box">

                            <h4 class="page-title">Contacts</h4>
                        </div>
                    </div>
                </div>
                <!-- end page title -->

                <div class="row">
                    <div class="col-12">
                        <div class="card-box">
                            <div class="row">
                                <div class="col-lg-8">
                                    <form class="form-inline">
                                        <div class="form-group">
                                            <label for="inputPassword2" class="sr-only">Search</label>
                                            <input type="search" class="form-control" id="inputPassword2"
                                                placeholder="Search...">
                                        </div>
                                        <div class="form-group mx-sm-3">
                                            <label for="status-select" class="mr-2">Sort By</label>
                                            <select class="custom-select" id="status-select">
                                                <option selected="">All</option>
                                                <option value="1">Name</option>
                                                <option value="2">Post</option>
                                                <option value="3">Followers</option>
                                                <option value="4">Followings</option>
                                            </select>
                                        </div>
                                    </form>
                                </div>
                                <!-- end col-->
                            </div> <!-- end row -->
                        </div> <!-- end card-box -->
                    </div><!-- end col-->
                </div>
                <!-- end row -->

                <div class="row">
                    @foreach ($jobs as $job)
                        <div class="col-lg-4">
                            <div class="text-center card-box">
                                <div class="pt-2 pb-2">
                                    
                                    <h4 class="mt-3"><a href="extras-profile.html"
                                            class="text-light">{{ $job->title }}</a></h4>
                                     <p class="text-muted">Location:<span class="text-pink">{{ $job->location }}</span></p>
                                    <a href="{{ route('job.show', $job->id) }}"
                                        class="btn btn-primary btn-sm waves-effect waves-light">Details</a>
                                    <a href="{{ route('job.destroy', $job->id) }}"
                                        class="btn btn-danger btn-sm waves-effect waves-light">Delete</a>
                                </div> <!-- end .padding -->
                            </div> <!-- end card-box-->
                        </div>
                    @endforeach
              </div>
                <div class="row">
                    <div class="col-12">
                        <div class="text-right">
                            <ul class="pagination pagination-rounded justify-content-end">
                                <li class="page-item">
                                    <a class="page-link" href="javascript: void(0);" aria-label="Previous">
                                        <span aria-hidden="true">«</span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                </li>
                                <li class="page-item active"><a class="page-link" href="javascript: void(0);">1</a></li>
                                <li class="page-item"><a class="page-link" href="javascript: void(0);">2</a></li>
                                <li class="page-item"><a class="page-link" href="javascript: void(0);">3</a></li>
                                <li class="page-item"><a class="page-link" href="javascript: void(0);">4</a></li>
                                <li class="page-item"><a class="page-link" href="javascript: void(0);">5</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="javascript: void(0);" aria-label="Next">
                                        <span aria-hidden="true">»</span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div> <!-- container -->
        </div> <!-- content -->
    </div>
@endsection

resources/views/frontend/pages/job/job_details.blade.php
@extends('frontend.layouts.master')
@section('content')
    <div class="content-page">
        <div class="content">

            <!-- Start Content-->
            <div class="container-fluid">

                <!-- start page title -->
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box">
                            <div class="card-box">
                                @if (session('success'))
                                <div class="alert alert-success">
                                    {{ session('success') }}
                                </div>
                            @endif
                            
                            @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            </div>
                          
                            <h4 class="page-title">Job Details given, Please apply from below.</h4>
                        </div>
                    </div>
                </div>
                <!-- end page title -->

                <div class="row">
                    <div class="col-12">
                        <div class="card-box">
                            <div class="row">
                                <!-- end col -->
                                <div class="col-xl-8">
                                    <div class="pl-xl-3 mt-3 mt-xl-0">
                                        <a href="#" class="text-primary">@php dd($applicant_list);
                                        @endphp
                                        </a>
                                       
                                        <h4 class="mb-3"></h4>
                                        <label>Job Deadline :</label>
                                        <h6 class="text-danger text-uppercase">{{ $job->job_deadline }}</h6>
                                        <h4 class="mb-4">Job Title : <span class="text-muted mr-2"></span>
                                            <b>{{ $job->title }}</b>
                                        </h4>
                                        <div class="row mb-3">
                                            <div class="col-md-12">
                                                <div>
                                                    <b>Job Description:</b>
                                                    {!! $job->description !!}

                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <b>Gender:</b>
                                                {{ $job->gender }}
                                            </div>
                                            <div class="col-md-6">
                                                <b>Job Category:</b>
                                                {{ $job->job_category }}
                                            </div>

                                            <div class="col-md-6">
                                                <b>Job Qualifications:</b>
                                                {{ $job->job_qualification }}
                                            </div>
                                            <div class="col-md-6">
                                                <b>Job Location:</b>
                                                {{ $job->location }}
                                            </div>
                                            <div class="col-md-6">
                                                <b>Salary Range:</b>
                                                {{ $job->salary_range }} BDT
                                            </div>
                                            <div class="col-md-12">
                                                @if (auth()->check())
                                                    <h3>Your Expected Salary*</h3>

                                                    <form action="{{ route('appliedjob.store') }}" method="post">
                                                        @csrf
                                                        <div class="row">
                                                            <input type="hidden" name="job_id"
                                                                value="{{ old('job_id', $job->id) }}">
                                                            <div class="pl-xl-3 mt-3 mt-xl-0"><input type="number"
                                                                    placeholder="e.g.20000" name="salary">
                                                            </div>
                                                            <div class="pl-xl-3 mt-3 mt-xl-0"><input type="hidden"
                                                                    value="" name="email">
                                                            </div>


                                                            <button type="submit"
                                                                class="btn w-sm btn-danger waves-effect waves-light">Apply</button>
                                                        </div>
                                                    </form>
                                                @else
                                                    <a href="{{ route('login') }}" class="btn btn-primary">Apply Online
                                                    </a>
                                                @endif



                                            </div>

                                        </div>

                                    </div>
                                </div>
                                <div>
                                    <div class="form-group">
                                        <div class="pl-xl-3 mt-3 mt-xl-0">
                                            <h3>Website:<span><a href="https://www.anhgroupbd.com/">anhgroup.com</span></h3>

                                        </div>
                                    </div>
                                    <div class="form-group">

                                    </div>
                                </div> <!-- end col -->
                            </div>
                            <!-- end row -->
                        </div> <!-- end card-->
                    </div>
                    <div>
                        <h1><u> Information</u><br /> </h1>
                        <p>AnH Enterprise Limited:
                            House# 04 , Probal Housing, Ring Road, Mohammadpur, Dhaka-1207, Bangladesh
                            Web: www.anhenterprise.com</p>

                    </div>



                    <!-- end col-->
                </div>
                <!-- end row-->

            </div> <!-- container -->

        </div> <!-- content -->


    </div>
@endsection